trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
  resourceGroupName: 'ap-dev-apollo2-smartpos-rg'
  location: 'eastasia'
  storageAccountName: 'apdevapollo2possmart01'
  containerName: 'posinventorycontainer'
  configTableName: 'InventoryFlowSettings'
  lookupTableName: 'StoreSmartPosLookup'

steps:
- script: echo start create development infrastructure!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      if [ $(az group exists --name $resourceGroup) = false ]; then 
        az group create  --location $location --resource-group  $resourceGroupName
      else
        echo $resourceGroup is existing
      fi