trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
  resourceGroup: 'dev12-smartpos-rg'
  location: 'southindia'               # e.g., 'eastus'
  storageAccount: 'dev12smartposstorageac'      # Unique name for the storage account
  dataFactory: 'dev12smartposadf'         # Name for the Azure Data Factory
  keyVault: 'dev12smartposkeyvalut'               # Unique name for the Azure Key Vault
  functionAppName: 'dev12smartposfunctionapp'     # Unique name for the Azure Function App
  tableStorageName: 'devsmartpos12lookuptable'           # Name for the Azure Table Storage
  blobContainerName: 'devsmartposcontainer'         # Name for the Azure Blob Storage container
  IsLinux : false
  runtime: 'dotnet'
  sku: 'EP1' 
stages:
- stage: CreateResources
  jobs:
  - job: CreateAzureResources
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline: |
         ge Blob Data Contributor" --scope /subscriptions/$(subscriptionId)/resourceGroups/$(fallbackResourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(fallbackStorageAccountName)
         az role assignment create --assignee $principalId --role "Storage Table Data Contributor" --scope /subscriptions/$(subscriptionId)/resourceGroups/$(fallbackResourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(fallbackStorageAccountName)
          }
          
        
        azurePowerShellVersion: 'LatestVersion'
