trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
  resourceGroup: 'dev5-smartpos-rg'
  dataFactoryName: 'dev5smartposadf'     # Name of the Azure Data Factory
  keyVaultName: 'dev5smartposkeyvalut'           # Name of the Azure Key Vault

stages:
- stage: GrantDataFactoryAccess
  jobs:
  - job: GrantAccess
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline: |
          # Get the Data Factory's Managed Identity
          $dataFactory = Get-AzDataFactoryV2 -ResourceGroupName $(resourceGroup) -Name $(dataFactoryName)
          $identity = $dataFactory.Identity.PrincipalId

          # Define Key Vault access policy
          $accessPolicy = New-AzKeyVaultAccessPolicy -ObjectId $identity -PermissionsToSecrets get, list

          # Get the Key Vault
          $keyVault = Get-AzKeyVault -ResourceGroupName $(resourceGroup) -VaultName $(keyVaultName)

          # Set the access policy for the Data Factory
          Set-AzKeyVaultAccessPolicy -VaultName $(keyVaultName) -AccessPolicy $accessPolicy
          
          Write-Output "Granted Azure Data Factory '$($dataFactoryName)' access to Key Vault '$($keyVaultName)'."
        
          azurePowerShellVersion: 'LatestVersion'
