trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'  # Azure service connection name
  resourceGroup: 'ap-dev-apollo2-smartpos-rg'          # Desired resource group name
  location: 'eastasia'               # e.g., 'eastus'

stages:
- stage: CreateResourceGroup
  jobs:
  - job: CreateRG
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline: |
          # Check if the resource group exists
          $resourceGroupExists = Get-AzResourceGroup -Name $(resourceGroup) -ErrorAction SilentlyContinue

          if (-not $resourceGroupExists) {
              # Create the resource group
              New-AzResourceGroup -Name $(resourceGroup) -Location $(location)
              Write-Output "Resource Group '$(resourceGroup)' created successfully."
          } else {
              Write-Output "Resource Group '$(resourceGroup)' already exists."
          }
        azurePowerShellVersion: 'LatestVersion'
