trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
  resourceGroup: 'dev12-smartpos-rg'
  location: 'southindia'               # e.g., 'eastus'
  storageAccount: 'dev12smartposstorageac'      # Unique name for the storage account
  dataFactory: 'dev12smartposadf'         # Name for the Azure Data Factory
  keyVault: 'dev12smartposkeyvalut'               # Unique name for the Azure Key Vault
  functionAppName: 'dev12smartposfunctionapp'     # Unique name for the Azure Function App
  tableStorageName: 'devsmartpos12lookuptable'           # Name for the Azure Table Storage
  blobContainerName: 'devsmartposcontainer'         # Name for the Azure Blob Storage container
  IsLinux : false
stages:
- stage: CreateResources
  jobs:
  - job: CreateAzureResources
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptType: 'InlineScript'
        Inline: |
          # Check if the resource group exists
          $resourceGroupExists = Get-AzResourceGroup -Name $(resourceGroup) -ErrorAction SilentlyContinue

          if (-not $resourceGroupExists) {
              # Create the resource group
              New-AzResourceGroup -Name $(resourceGroup) -Location $(location)
              Write-Output "Resource Group '$(resourceGroup)' created successfully."
          } else {
              Write-Output "Resource Group '$(resourceGroup)' already exists."
          }

          # Create Storage Account
          $storageAccountExists = Get-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount) -ErrorAction SilentlyContinue

          if (-not $storageAccountExists) {
              New-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount) -Location $(location) -SkuName Standard_LRS -Kind StorageV2
              Write-Output "Storage Account '$(storageAccount)' created successfully in resource group '$(resourceGroup)'."
          } else {
              Write-Output "Storage Account '$(storageAccount)' already exists in resource group '$(resourceGroup)'."
          }
         
          # Create Azure Data Factory
          $dataFactoryExists = Get-AzDataFactoryV2 -ResourceGroupName $(resourceGroup) -Name $(dataFactory) -ErrorAction SilentlyContinue

          if (-not $dataFactoryExists) {
              New-AzDataFactoryV2 -ResourceGroupName $(resourceGroup) -Name $(dataFactory) -Location $(location)
              Write-Output "Azure Data Factory '$(dataFactory)' created successfully in resource group '$(resourceGroup)'."
          } else {
              Write-Output "Azure Data Factory '$(dataFactory)' already exists in resource group '$(resourceGroup)'."
          }

          # Create Key Vault
          $keyVaultExists = Get-AzKeyVault -ResourceGroupName $(resourceGroup) -VaultName $(keyVault) -ErrorAction SilentlyContinue

          if (-not $keyVaultExists) {
              New-AzKeyVault -ResourceGroupName $(resourceGroup) -VaultName $(keyVault) -Location $(location) -Sku 'Standard'
              Write-Output "Key Vault '$(keyVault)' created successfully in resource group '$(resourceGroup)'."
          } else {
              Write-Output "Key Vault '$(keyVault)' already exists in resource group '$(resourceGroup)'."
          }
          # Create Table Storage 
          $tableService = New-AzStorageTable -Name $(tableStorageName) -Context (Get-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount)).Context
          Write-Output "Table Storage '$($tableStorageName)' created successfully in Storage Account '$($storageAccount)'."

          # Create Blob Container
          # $blobContainerExists = Get-AzStorageContainer -ContainerName $(blobContainerName) -Context (Get-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount)).Context -ErrorAction SilentlyContinue
            $blobContainerExists = Get-AzStorageContainer -Container $(blobContainerName) -Context (Get-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount)).Context -ErrorAction SilentlyContinue

          if (-not $blobContainerExists) {
              New-AzStorageContainer -Name $(blobContainerName) -Context (Get-AzStorageAccount -ResourceGroupName $(resourceGroup) -Name $(storageAccount)).Context -PublicAccess Off
              Write-Output "Blob Container '$($blobContainerName)' created successfully in Storage Account '$($storageAccount)'."
          } else {
              Write-Output "Blob Container '$($blobContainerName)' already exists in Storage Account '$($storageAccount)'."
          }
          # Check if the Function App exists
          $functionAppExists = Get-AzFunctionApp -ResourceGroupName $(resourceGroup) -Name $(functionAppName) -ErrorAction SilentlyContinue

          if (-not $functionAppExists) {
              # Create Function App
              New-AzFunctionApp -ResourceGroupName $(resourceGroup) -Name $(functionAppName) -Location $(location) -storageAccount $(storageAccount) -Runtime $(runtime) -Sku $(sku)
              Write-Output "Function App '$(functionAppName)' created successfully in resource group '$(resourceGroup)'."
          } else {
              Write-Output "Function App '$(functionAppName)' already exists in resource group '$(resourceGroup)'."
          }

          # Create Function App
          $functionAppExists = Get-AzFunctionApp -ResourceGroupName $(resourceGroup) -Name $(functionAppName) -ErrorAction SilentlyContinue

          if (-not $functionAppExists) {
              # Create a Consumption Plan for the Function App
              $planName = "$(functionAppName)-plan"
              New-AzFunctionAppPlan -ResourceGroupName $(resourceGroup) -Name $planName -Location $(location) -Sku 'EP1'-WorkerType Windows
             
              # Create the Function App
              New-AzFunctionApp -ResourceGroupName $(resourceGroup) -Name $(functionAppName) -Location $(location) -StorageAccountName $(storageAccount) -Plan $planName -Runtime 'dotnet' -FunctionsVersion '3'
              Write-Output "Function App '$(functionAppName)' created successfully in resource group '$(resourceGroup)'."
          } else {
              Write-Output "Function App '$(functionAppName)' already exists in resource group '$(resourceGroup)'."
          }
        
        azurePowerShellVersion: 'LatestVersion'
