trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
  resourceGroup: 'msdocs-azure-functions-rg'
  functionAppName: 'msdocs-serverless-function'
  storageAccount: 'msdocsaccount'
  location: 'eastus'
  runtime: 'node'  # or 'dotnet', 'python', etc.

stages:
- stage: Deploy
  jobs:
  - job: DeployAzureFunction
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Log in to Azure
          echo "Logging in to Azure"
          az account set --subscription $(azureSubscription)

          # Create Resource Group if it does not exist
          echo "Creating Resource Group"
          az group create --name $(resourceGroup) --location $(location)

          # Create Storage Account
          echo "Creating Storage Account"
          az storage account create --name $(storageAccount) --location $(location) --resource-group $(resourceGroup) --sku Standard_LRS

          # Create Function App
          echo "Creating Function App"
          az functionapp create --resource-group $(resourceGroup) --consumption-plan-location $(location) --runtime $(runtime) --functions-version 3 --name $(functionAppName) --storage-account $(storageAccount)

          echo "Deployment complete."
