# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Professional(cb9ac514-a7d4-4892-8b9d-537c4ad22fb3)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Function app and storage account names must be unique.
      
      # Variable block
      $randomIdentifier = Get-Random
      $location = "eastus"
      $resourceGroup = "msdocs-azure-functions-rg-$randomIdentifier"
      $tag = @{script = "create-function-app-consumption-python"}
      $storage = "msdocsaccount$randomIdentifier"
      $functionApp = "msdocs-serverless-python-function-$randomIdentifier"
      $skuStorage = "Standard_LRS"
      $functionsVersion = "4"
      $pythonVersion = "3.9" #Allowed values: 3.7, 3.8, and 3.9
      
      # Create a resource group
      Write-Host "Creating $resourceGroup in $location..."
      New-AzResourceGroup -Name $resourceGroup -Location $location -Tag $tag
      
      # Create an Azure storage account in the resource group.
      Write-Host "Creating $storage"
      New-AzStorageAccount -Name $storage -Location $location -ResourceGroupName $resourceGroup -SkuName $skuStorage
      
      # Create a serverless Python function app in the resource group.
      Write-Host "Creating $functionApp"
      New-AzFunctionApp -Name $functionApp -StorageAccountName $storage -Location $location -ResourceGroupName $resourceGroup -OSType Linux -Runtime Python -RuntimeVersion $pythonVersion -FunctionsVersion $functionsVersion