trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Define the parameters for the ARM template
      $resourceGroupName = "myResourceGroup"
      $location = "East US"

      # Define the ARM template structure
      $armTemplate = @{
          "$schema" = "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"
          "contentVersion" = "1.0.0.0"
          "resources" = @(
              @{
                  "type" = "Microsoft.Resources/resourceGroups"
                  "apiVersion" = "2021-04-01"
                  "name" = $resourceGroupName
                  "location" = $location
              }
          )
      }

      # Convert the ARM template to JSON
      $jsonTemplate = $armTemplate | ConvertTo-Json -Depth 100
      
      # Save the JSON to a file
      $templatePath = "$(Build.ArtifactStagingDirectory)\armTemplate.json"
      $jsonTemplate | Out-File -FilePath $templatePath -Encoding utf8

      Write-Host "ARM template generated at: $templatePath"
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ArmTemplate'
    publishLocation: 'Container'
